package com.example.studentes

 class ModelSignin : ArrayList<ModelSigninItem>()

data class ModelSigninItem(
    val `0`: String,
    val `1`: String,
    val `10`: String,
    val `11`: String,
    val `12`: String,
    val `13`: String,
    val `14`: String,
    val `15`: String,
    val `16`: String,
    val `17`: String,
    val `18`: String,
    val `19`: String,
    val `2`: String,
    val `20`: String,
    val `3`: String,
    val `4`: String,
    val `5`: String,
    val `6`: String,
    val `7`: String,
    val `8`: String,
    val `9`: String,
    val address: String,
    val app: String,
    val app_id: String,
    val cancel: String,
    val course_id: String,
    val dip: String,
    val email: String,
    val id_a: String,
    val image: String,
    val name: String,
    val name_ar: String,
    val national_id: String,
    val phone: String,
    val phone_n: String,
    val rev: String,
    val ses_id: String,
    val st_id: String,
    val start: String,
    val state: String,
    val sw: String,
    val time: String
)